### ISSUE TITLE
Start DET server fails with: port must be an integer

### ISSUE THREAD

**Issue by Nyna71** [jpoullet2000/det#5]
Traceback (most recent call last):
  File "/home/det/det/bin/det", line 15, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/det/det/cli.py", line 47, in runserver
    APP.run(port=port)
  File "/usr/local/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 94, in run
    self.app.run(self.host, port=self.port, debug=self.debug, **options)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 748, in run_simple
    raise TypeError('port must be an integer')
TypeError: <flask_script.commands.Command object at 0x7f2dfbe3dc50>: port must be an integer

**Comment by jpoullet2000** [comment]
I'm converting it now in int (see f95a5513d34ec18bfa9adfab7ae0c13abd85b808)
